site_name: Boko Hacks
site_url: https://bokohacks.com
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
nav:
  - Home: index.md
  - About : about.md
  - Event Archive: archive.md
  - Sponsors: thankyou.md
  - Directors: directors.html
extra_javascript:
  - javascripts/main.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/animations.css
  - stylesheets/directors.css

extra:
  cname: bokohacks.com